org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.java.home=/home/geno1024/.jdks/openjdk-25.0.2
org.gradle.java.installations.paths=/home/geno1024/.jdks/openjdk-25.0.2

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
