package com.geno1024.pictureframe.update

/**
 * Metadata for the rolling canary build, published next to the APK as a
 * `canary.properties` asset.
 *
 * The format is deliberately flat `key=value` rather than JSON: the values are
 * simple tokens with nothing to escape, and it keeps the app free of a
 * serialization dependency while staying parseable by the JVM unit tests.
 */
data class CanaryInfo(
    val runNumber: Int,
    val versionName: String,
    val sizeBytes: Long,
    val sha256: String,
    val assetName: String,
) {
    val shortSha: String get() = sha256.take(8)
}

object CanaryManifest {

    const val ASSET_NAME = "canary.properties"

    private val REPO = "Geno1024-AIGC/picture-frame-android"
    private val TAG = "canary"

    /** Direct GitHub URL for the manifest. Kept small so a slow fetch still works. */
    val DIRECT_URL: String =
        "https://github.com/$REPO/releases/download/$TAG/$ASSET_NAME"

    val DIRECT_APK_URL: String =
        "https://github.com/$REPO/releases/download/$TAG/app-debug.apk"

    fun apkUrl(): String = DIRECT_APK_URL

    fun parse(text: String): CanaryInfo? {
        val values = HashMap<String, String>()
        for (rawLine in text.lineSequence()) {
            val line = rawLine.trim()
            if (line.isEmpty() || line.startsWith("#") || line.startsWith("!")) continue
            val separator = line.indexOf('=')
            if (separator <= 0) continue
            values[line.substring(0, separator).trim()] = line.substring(separator + 1).trim()
        }
        val runNumber = values["runNumber"]?.toIntOrNull() ?: return null
        val sha256 = values["sha256"]?.lowercase()?.takeIf { it.length == 64 }
            ?.takeIf { it.all { c -> c in '0'..'9' || c in 'a'..'f' } }
            ?: return null
        val size = values["sizeBytes"]?.toLongOrNull() ?: 0L
        return CanaryInfo(
            runNumber = runNumber,
            versionName = values["versionName"].orEmpty().ifEmpty { "canary" },
            sizeBytes = size,
            sha256 = sha256,
            assetName = values["assetName"].orEmpty().ifEmpty { "app-debug.apk" },
        )
    }

    /** Renders the manifest that CI uploads to the release. */
    fun render(info: CanaryInfo, commit: String): String = buildString {
        appendLine("# Generated by the Build workflow. Consumed by the in-app updater.")
        appendLine("runNumber=${info.runNumber}")
        appendLine("versionName=${info.versionName}")
        appendLine("sizeBytes=${info.sizeBytes}")
        appendLine("sha256=${info.sha256}")
        appendLine("assetName=${info.assetName}")
        appendLine("commit=${commit}")
    }
}
