package com.geno1024.pictureframe.update

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class CanaryManifestTest {

    private val good = """
        # Generated by the Build workflow. Consumed by the in-app updater.
        runNumber=8
        versionName=1.0
        sizeBytes=12010164
        sha256=b586d0ff14400de6c634444a7051b12777f77259e09bf42e6e9c3b50527a3d8a
        assetName=app-debug.apk
        commit=0daf5109a9b221df5b5b1b9d25c3745b198c22f4
    """.trimIndent()

    @Test
    fun parsesEveryField() {
        val info = CanaryManifest.parse(good)!!
        assertEquals(8, info.runNumber)
        assertEquals("1.0", info.versionName)
        assertEquals(12010164L, info.sizeBytes)
        assertEquals("b586d0ff", info.shortSha)
        assertEquals("app-debug.apk", info.assetName)
    }

    @Test
    fun toleratesBlankLinesCommentsAndSurroundingSpace() {
        val info = CanaryManifest.parse(
            """

              # a comment
              ! another comment style

                runNumber = 12
                versionName= 1.0
                sizeBytes = 99
                sha256 = B586D0FF14400DE6C634444A7051B12777F77259E09BF42E6E9C3B50527A3D8A
            """.trimIndent(),
        )!!
        assertEquals(12, info.runNumber)
        assertEquals(99L, info.sizeBytes)
        assertEquals("b586d0ff", info.shortSha)
    }

    @Test
    fun fallsBackWhenOptionalFieldsAreMissing() {
        val info = CanaryManifest.parse(
            "runNumber=3\nsha256=${"a".repeat(64)}\n",
        )!!
        assertEquals(3, info.runNumber)
        assertEquals("canary", info.versionName)
        assertEquals(0L, info.sizeBytes)
        assertEquals("app-debug.apk", info.assetName)
    }

    @Test
    fun rejectsAMissingOrNonNumericRunNumber() {
        assertNull(CanaryManifest.parse("runNumber=abc\n"))
        assertNull(CanaryManifest.parse("versionName=1.0\n"))
    }

    @Test
    fun rejectsADigestThatIsNotHexOrIsWrongLength() {
        assertNull(CanaryManifest.parse("runNumber=1\nsha256=${"z".repeat(64)}\n"))
        assertNull(CanaryManifest.parse("runNumber=1\nsha256=deadbeef\n"))
        assertNull(CanaryManifest.parse("runNumber=1\n"))
    }

    @Test
    fun renderThenParseRoundTrips() {
        val info = CanaryManifest.parse(good)!!
        val text = CanaryManifest.render(info, commit = "0daf5109a9b221df5b5b1b9d25c3745b198c22f4")
        val again = CanaryManifest.parse(text)!!
        assertEquals(info, again)
        assertTrue(text.contains("commit=0daf5109"))
    }

    @Test
    fun theManifestUrlPointsAtTheRollingCanaryTag() {
        assertTrue(CanaryManifest.DIRECT_URL.startsWith("https://github.com/"))
        assertTrue(CanaryManifest.DIRECT_URL.endsWith("/releases/download/canary/canary.properties"))
        assertTrue(CanaryManifest.apkUrl().endsWith("/releases/download/canary/app-debug.apk"))
    }
}

class MirrorTest {

    @Test
    fun directLeavesTheUrlAlone() {
        assertEquals(
            "https://github.com/a/b/releases/download/canary/app-debug.apk",
            Mirrors.DIRECT.wrap("https://github.com/a/b/releases/download/canary/app-debug.apk"),
        )
    }

    @Test
    fun aPrefixProxyPrependsTheMirror() {
        val mirror = Mirror("gh-proxy.com", "https://gh-proxy.com")
        assertEquals(
            "https://gh-proxy.com/https://github.com/a/b/app.apk",
            mirror.wrap("https://github.com/a/b/app.apk"),
        )
    }

    @Test
    fun aTrailingSlashOnThePrefixDoesNotDoubleUp() {
        val mirror = Mirror("m", "https://gh-proxy.com/")
        assertEquals(
            "https://gh-proxy.com/https://github.com/a/b.apk",
            mirror.wrap("https://github.com/a/b.apk"),
        )
    }

    @Test
    fun resolveReturnsThePresetSoTheLabelStaysFriendly() {
        val preset = Mirrors.PRESETS.first { it.prefix == "https://ghproxy.net" }
        assertEquals(preset, Mirrors.resolve("https://ghproxy.net"))
    }

    @Test
    fun resolveAcceptsAnUnknownPrefixAsCustom() {
        val custom = Mirrors.resolve("  https://my.mirror.example  ")
        assertEquals("自定义", custom.label)
        assertEquals("https://my.mirror.example", custom.prefix)
    }

    @Test
    fun directIsAlwaysTheFirstChoice() {
        assertEquals(Mirrors.DIRECT, Mirrors.PRESETS.first())
    }
}
